package org.example

import com.example.demo.Models.SituacaoAnimalModel;
import com.example.demo.Models.RulerModel;

rule "Verifica batimentos OK"
no-loop true
dialect "java"
	when
		$SituacaoAnimalModel: SituacaoAnimalModel(batimentos < 160)
	then
	    System.out.println("\n esta normal \n");
	    drools.halt();
end

rule "Batimentos fora do normal"
no-loop true
dialect "java"
	when
		$SituacaoAnimalModel: SituacaoAnimalModel(batimentos > 160)
	then
	    System.out.println("\n\n\n\n esta fora normal\n\n\n\n");
end

